import { Clock3, Play, Trash2 } from "lucide-react"
import { useState } from "react"
import { Tabs } from "radix-ui"

import { DownloadRow, useDownloads } from "@/components/downloads"
import { MediaCard, bookmarkToSummary } from "@/components/media-card"
import { CollectionEmpty, PageContainer } from "@/components/page-state"
import { Button } from "@/components/ui/button"
import { useLibrary } from "@/hooks"
import { navigate } from "@/lib/router"

export function LibraryPage() {
  const library = useLibrary()
  const downloads = useDownloads()
  const [message, setMessage] = useState<string | null>(null)
  const tabs = [{ value: "saved", label: "Saved", count: library.bookmarks.length }, { value: "history", label: "History", count: library.history.length }, { value: "downloads", label: "Downloads", count: downloads.length }]
  return <PageContainer className="py-8 sm:py-12"><p className="eyebrow">Your space</p><h1 className="page-title">Library</h1><Tabs.Root defaultValue="saved" className="mt-8"><Tabs.List aria-label="Library sections" className="flex gap-1 overflow-x-auto border-b border-border">{tabs.map((tab) => <Tabs.Trigger key={tab.value} value={tab.value} className="min-h-12 border-b-2 border-transparent px-4 text-sm font-medium text-muted-foreground outline-none transition-colors hover:text-foreground focus-visible:ring-2 focus-visible:ring-ring data-[state=active]:border-primary data-[state=active]:text-foreground">{tab.label}<span className="ml-2 text-xs tabular-nums">{tab.count}</span></Tabs.Trigger>)}</Tabs.List>
      <Tabs.Content value="saved" className="pt-7 outline-none">{library.bookmarks.length ? <div className="media-grid">{library.bookmarks.map((item) => <MediaCard key={item.imdbId} media={bookmarkToSummary(item)} />)}</div> : <CollectionEmpty title="Nothing saved yet" description="Add titles to your library to keep them close." />}</Tabs.Content>
      <Tabs.Content value="history" className="pt-7 outline-none">{library.history.length ? <div className="space-y-3"><div className="flex justify-end"><Button variant="ghost" onClick={library.clearHistory}>Clear history</Button></div>{library.history.map((record) => { const id = record.media.imdbId || record.media.id; return <article key={`${id}-${record.season}-${record.episode}`} className="flex items-center gap-4 rounded-xl border border-border bg-card p-3 sm:p-4"><div className="hidden aspect-video w-28 overflow-hidden rounded-md bg-muted sm:block">{record.media.backdropUrl || record.media.posterUrl ? <img src={record.media.backdropUrl || record.media.posterUrl || ""} alt="" className="h-full w-full object-cover" /> : null}</div><div className="min-w-0 flex-1"><h3 className="truncate font-semibold">{record.media.title}</h3><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><Clock3 className="size-3.5" />{record.season !== null ? `S${record.season} E${record.episode} · ` : ""}{Math.round(record.positionSeconds / 60)} min watched</p></div><Button size="icon" variant="ghost" aria-label={`Remove ${record.media.title} from history`} onClick={() => library.removeHistory(id, record.season, record.episode)}><Trash2 /></Button><Button size="icon" aria-label={`Continue ${record.media.title}`} onClick={() => navigate(record.season !== null && record.episode !== null ? { name: "watch", imdbId: id, season: record.season, episode: record.episode } : { name: "watch", imdbId: id })}><Play /></Button></article>})}</div> : <CollectionEmpty title="No watch history" description="Titles you play will appear here." />}</Tabs.Content>
      <Tabs.Content value="downloads" className="pt-7 outline-none">{message ? <p role="alert" className="mb-4 rounded-lg border border-destructive/40 bg-destructive/10 p-3 text-sm">{message}</p> : null}{downloads.length ? <div className="space-y-3">{downloads.map((manifest) => <DownloadRow key={manifest.id} manifest={manifest} onError={setMessage} onPlay={() => { sessionStorage.setItem("hawk.playOffline", manifest.id); const imdbId = String(manifest.metadata.imdbId ?? manifest.id); const season = typeof manifest.metadata.season === "number" ? manifest.metadata.season : null; const episode = typeof manifest.metadata.episode === "number" ? manifest.metadata.episode : null; navigate(season !== null && episode !== null ? { name: "watch", imdbId, season, episode } : { name: "watch", imdbId }) }} />)}</div> : <CollectionEmpty title="No downloads" description="Download a playing title to watch it without a connection." />}</Tabs.Content>
    </Tabs.Root></PageContainer>
}
